name: Node CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn run lint
        yarn run build
        yarn run coverage
        yarn run size
      env:
        CI: true
